### ISSUE TITLE
Command sent by Selection when sitemap loaded

### ISSUE THREAD

**Issue by dougmeredith** [openhab/openhab.android#53] opened 2015-02-03 20:00 UTC
Here is a simple example:

String junk {autoupdate="false"}

sitemap demo label="House"
{
        Frame label="Information" {
                Selection item=junk label="Alarm ready to arm"  mappings=[home=home,arm_away=away]
        }
}

Immediately upon loading this sitemap in habdroid, the item "junk" receives the command "home".

The web UI does not exhibit this behavior.

Note: Based on some quick testing, the problem does not occur if autoupdates are enabled.

**Comment by Tomtibo** [comment] 2015-02-03 20:23
Same here with 3 of my Selections, I'v try with 2 devices running lolipop with same result. I'v also try to add option autoupdate="false" in the item binding without result.

**Comment by hlat** [comment] 2015-02-16 21:44
Same here with selection and squeezbox Binding on IOS App.

**Comment by belovictor** [comment] 2015-03-23 12:25
This is caused by android spinner behaviour. When rendered it always calls onItemSelected. There is a protection mechanism in the app from false commands which checks if onItemSelected selects a command different from the current state. So it should not send any commands. The only case I can see here if your Item's state is uninitialized and thus the app thinks that selected spinner item would change the state and because of that sends the command. Am I right?

**Comment by Tomtibo** [comment] 2015-03-27 22:30
I guess you're right! I've been doing some troubleshoot after reading your post and find out some interesting facts. 
If an onItemsSelected send command and receive an identical status update, then the next sitemap loading will not send command and the selection stay at the previously selected item.
If an onItemsSelected send command and receive a different status update, then the next sitemap loading will select the firstItemListed and send his command.
If an onItemsSelected send command and don't receive a status update, then the next sitemap loading will not send command and the selection stay at the previously selected item.
So I think it's not an HABdroid or IOSApp fault, but a binding or config problem. I still try to fingure out a workaround, config, script, rules to avoid this problem because, in many case, I'm not always receive an identical status update for an item.

**Comment by belovictor** [comment] 2015-04-01 11:08
Ok, I'm closing this then, feel free to reopen or open a new issue in case you find something on the mobile apps side!

**Closed by belovictor** 2015-04-01 11:08 UTC
