### ISSUE TITLE
Mutual SSL - client certificate authentication

### ISSUE THREAD

**Issue by tulamidan** [openhab/openhab.android#230] opened 2016-10-03 02:32 UTC
When using a reverse proxy configured for mutual SSL authentication, the HABDroid client only responds with a "HTTP Error - Bad Request" to the certificate challenge.

Expected Behavior

The Habdroid client let's you pick a certificate from your certificate store.

Current Behavior

The error message above

Possible Solution

Add support for mutual SSL

Context

Thoug creating your own certificates is not the most common thing for a regular user - it is a smart, secure and convenient way to allow internet access to your OH Server. No need for passwords.

Your Environment

OH on Raspi, NGINX 1.6.1 (reverse proxy) on Raspi/Docker, with mutual SSL (works for OH if you stay browser based)
##

**Comment by slawekjaranowski** [comment] 2016-10-03 06:56
I think it is connected with: #109

**Comment by tulamidan** [comment] 2016-10-03 08:37
Right, my bad I didn't see this issue beforehand. If you wish I can assist with a backend to test

**Comment by slawekjaranowski** [comment] 2016-10-03 16:54
It will be very helpful, if you can help with tests.
I propose continue discussion in issue: #109

**Comment by digitaldan** [comment] 2016-11-15 17:14
Duplicate of #109

**Closed** 2016-11-15 17:14 UTC
