### ISSUE TITLE
variabel openHABBaseUrl is null after Screen rotation

### ISSUE THREAD

**Issue by fspiekermann** [openhab/openhab.android#222] opened 2016-09-14 12:27 UTC
How to reproduced this Error:
- Start on some page of the app
- Rotate the Screen
- Choose an Item of the Sitemenu(like 'Bindings')
- The app will throw a  java.net.MalformedURLException but don't will be closed
- After open an close the settings of the app everything will work fine until you rotate the screen again.

`09-14 13:21:24.493 2910-2910/org.openhab.habdroid E/AsyncHttpClient: getUrlWithQueryString encoding URL
   java.net.MalformedURLException: Protocol not found: nullrest/bindings
       at java.net.URL.<init>(URL.java:176)
       at java.net.URL.<init>(URL.java:125)
       at com.loopj.android.http.AsyncHttpClient.getUrlWithQueryString(AsyncHttpClient.java:338)
       at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:1078)
       at com.loopj.android.http.AsyncHttpClient.get(AsyncHttpClient.java:1037)
       at org.openhab.habdroid.ui.OpenHABBindingFragment.loadBindings(OpenHABBindingFragment.java:180)
       at org.openhab.habdroid.ui.OpenHABBindingFragment.onResume(OpenHABBindingFragment.java:128)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2005)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:926)
       at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1272)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1630)
       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
       at android.support.v4.view.ViewPager.dataSetChanged(ViewPager.java:946)
       at android.support.v4.view.ViewPager$PagerObserver.onChanged(ViewPager.java:2910)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at android.support.v4.view.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:276)
       at org.openhab.habdroid.ui.OpenHABFragmentPagerAdapter.openBindings(OpenHABFragmentPagerAdapter.java:159)
       at org.openhab.habdroid.ui.OpenHABMainActivity.openBindings(OpenHABMainActivity.java:768)
       at org.openhab.habdroid.ui.OpenHABMainActivity$3.onItemClick(OpenHABMainActivity.java:433)
       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
       at android.widget.AbsListView$3.run(AbsListView.java:3879)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

In the Exception you can see, the App tries to call nullrest/bindings, so I think the variabel `openHABBaseUrl` will be null.
Cause of this I started the debugger and you can see the variabel `openHABBaseUrl` is null after rotating the screen. I have set Breakpoints in line 159 of `OpenHABFragmentPagerAdapter` and in line 128 of `OpenHABBindingFragment`. These two points i choosed cause of the lines in the Exception.

Here some Screenshots:
Before rotating:
line 159 of `OpenHABFragmentPagerAdapter`: 
![bildschirmfoto 2016-09-14 um 13 41 40](https://cloud.githubusercontent.com/assets/19517116/18511927/dae2caa2-7a86-11e6-9ea3-4032a7ce1e2c.png)
ine 128 of `OpenHABBindingFragment`:
![bildschirmfoto 2016-09-14 um 13 41 58](https://cloud.githubusercontent.com/assets/19517116/18511950/f3b87298-7a86-11e6-8068-26cc7927339d.png)
In both screenshots you can see, that the `openHABBaseUrl` is set to a local IP.
After rotating:
line 159 of `OpenHABFragmentPagerAdapter`: 
![bildschirmfoto 2016-09-14 um 13 42 56](https://cloud.githubusercontent.com/assets/19517116/18511968/056d2c90-7a87-11e6-8c6d-6804b85779e5.png)
ine 128 of `OpenHABBindingFragment`:
![bildschirmfoto 2016-09-14 um 13 43 43](https://cloud.githubusercontent.com/assets/19517116/18511984/1b1eec4a-7a87-11e6-9309-b572a9d1b882.png)
Now the `openHABBaseUrl` is null
##

**Comment by FlorianSW** [comment] 2017-06-12 19:13
Isn't this fixed by PR #223 ?

**Comment by fspiekermann** [comment] 2017-06-19 09:01
For my case it is fixed. I tested it and the app never crashed again.

**Comment by mueller-ma** [comment] 2017-06-20 17:23
Can you close this issue?

**Comment by mueller-ma** [comment] 2017-12-05 20:27
Cannot reproduce, seems to be fixed.

**Closed by mueller-ma** 2017-12-05 20:27 UTC
Labels: bug
