### ISSUE TITLE
v1.7 very slow in HTTPS mode

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#125] opened 2015-06-25 21:18 UTC
When using HTTPS, HABdroid 1.7.0.1 is very slow to display the pages and displaying icons takes a huge time. In practice, the application is no more usable in HTTPS mode.

With HABdroid 1.5.1.1, the HTTPS mode is a little slower than the HTTP mode but absolutely usable.

There is a regression.

**Comment by kaikreuzer** [comment] 2015-06-26 05:55
I do not think that this is an issue of the Android app (see also https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openhab/Q-54-UDGXxo/fuTM0qKx0awJ). Does the Classic UI show the same effect? If so, better close this issue here and open one at https://github.com/openhab/openhab/issues

**Comment by lolodomo** [comment] 2015-06-26 06:30
I have no problem with classific UI. Normal response time even in HTTPS mode.

**Comment by kaikreuzer** [comment] 2015-06-26 06:36
Ok, then let's leave it here and have @belovictor look at it.

**Comment by cribskip** [comment] 2015-06-26 08:10
:+1: on this.

Turning local URL to HTTPS makes habdroid really slow - just like over my.openhab / mobile access.
Classic UI is fast as over HTTP.

Habdroid 1.7.0.1
openhab 1.7.0
Android 5.0.1

**Comment by lolodomo** [comment] 2015-06-27 08:53
There might be a problem with image caching when in HTTPS mode.
I don't know if this is the problem or if there are two different problems.

**Comment by belovictor** [comment] 2015-06-27 12:37
I can't reproduce it - in an exactly the same environment I have it working lightning fast with https :-O
So I'm afraid I need to have a look at a logcat from your android device at least ...

**Comment by belovictor** [comment] 2015-07-05 20:01
Can you get logcat from your device?

**Comment by belovictor** [comment] 2015-08-09 15:41
Can anybody with this kind of problem make a logcat from your android device?

**Comment by adrianmihai83** [comment] 2015-09-09 20:23
Logcat attached in #116

**Comment by Seb-** [comment] 2016-02-17 23:42
Same issue here, this is extremely annoying. My openhab server is on a raspberry pi 2 and I noticed it reached 100% CPU when using HTTPS from the Android App. The web interface is absolutely fine. And HTTP on Android is fine as well.

**Comment by digitaldan** [comment] 2016-05-24 21:21
Can anyone reproduce this with the latest android client?

**Comment by lolodomo** [comment] 2016-05-24 22:20
I cannot reproduce the problem now.
The only noticeable difference I can see between HTTP and HTTPS modes (on my local network) is the time to display the icons. It takes a little time with HTTPS while it is immediate with HTTP. But it remains reasonable.
Just an hypothesis: maybe icons are cached when in HTTP mode and not when in HTTPS mode ?

**Comment by digitaldan** [comment] 2016-06-05 04:32
I am closing , if this is still an issue please feel free to re open.

**Closed by digitaldan** 2016-06-05 04:32 UTC
