### ISSUE TITLE
Rollershutter icons don't display actual state

### ISSUE THREAD

**Issue by stdll** [openhab/openhab.android#573] opened 2017-12-29 22:29 UTC
After the 2.0.0 upgrade, the rollershutter items don't display the position of the rollershutters correctly. Instead they're displaying the "neutral" position as if no value has been set.

Everything works correctly when using the web-based Basic UI.

**Comment by mueller-ma** [comment] 2017-12-29 22:56
Duplicate of #543. Leaving this one open until #542 is merged.

**Closed** 2017-12-30 23:07 UTC
Labels: duplicate
