### ISSUE TITLE
Android app crashes with some SVG icons

### ISSUE THREAD

**Issue by Adminius** [openhab/openhab.android#338] opened 2017-07-22 08:55 UTC
Hello,

i use newest app from Play Store.
if i use <fan> or <fan_box> and SVG, then app crashes if i open a group with this item.
If i switch to PNG, it works.

**Comment by mueller-ma** [comment] 2017-07-22 11:54
Duplicate #330 ?
Do you use anywhere an icon which does not exist?

**Comment by Adminius** [comment] 2017-07-23 09:50
ohh....seems to be the duplicate. 
I don't know if i miss this pictures in a SVG format. How can i check if this svg icons exists?

**Comment by mueller-ma** [comment] 2017-07-23 09:53
Look in your sitemap and go to the group where the app crashes when you open it. Do you use any icon there which is not listed [here](http://docs.openhab.org/addons/iconsets/classic/readme.html)?

**Comment by Adminius** [comment] 2017-07-23 10:40
i use <fan_box> and/or <fan>
![image](https://user-images.githubusercontent.com/17052262/28498467-7ec259c8-6f9e-11e7-8055-58c4d4e37a71.png)
SVG works in a browser, but not in the app.
PNG works in a browser and in the app. 

all groups, that don't use this icons, works perfect.
But only two groups with fan icons cause crash

**Comment by mueller-ma** [comment] 2017-07-23 11:25
Yes. I can confirm this. When fan_box is used an the app shows svg, than it crashes

**Comment by mueller-ma** [comment] 2017-07-23 11:35
I compiled it with the fix for #330 but it still crashes. http://openhab/icon/fan_box?state=null&format=SVG returns the correct svg. Here is my stack trace on android 5:

```
07-23 13:32:31.624 20077-20790/org.openhab.habdroid I/MyWebImage: Cache for http://openhab/icon/fan_box?state=null&format=SVG is empty, getting image
07-23 13:32:31.654 20077-20789/org.openhab.habdroid I/MyWebImage: Cache for http://openhab/icon/alarm?state=OFF&format=SVG is empty, getting image
07-23 13:32:31.847 20077-20077/org.openhab.habdroid D/AndroidRuntime: Shutting down VM
07-23 13:32:31.848 20077-20077/org.openhab.habdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.openhab.habdroid, PID: 20077
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.makeRadialGradient(SVGAndroidRenderer.java:3360)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.decodePaintReference(SVGAndroidRenderer.java:3178)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.checkForGradientsAndPatterns(SVGAndroidRenderer.java:3148)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1063)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:301)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:333)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:587)
                                                                          at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SVGAndroidRenderer.java:270)
                                                                          at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:406)
                                                                          at com.caverock.androidsvg.SVG.renderToCanvas(SVG.java:384)
                                                                          at org.openhab.habdroid.util.MyWebImage.getBitmapFromSvgInputstream(MyWebImage.java:158)
                                                                          at org.openhab.habdroid.util.MyWebImage.getBitmapFromInputStream(MyWebImage.java:135)
                                                                          at org.openhab.habdroid.util.MyWebImage.access$000(MyWebImage.java:35)
                                                                          at org.openhab.habdroid.util.MyWebImage$1.onSuccess(MyWebImage.java:107)
                                                                          at org.openhab.habdroid.util.MyAsyncHttpClient$1$2.run(MyAsyncHttpClient.java:70)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by jurviz** [comment] 2017-08-13 13:25
The app also crashes when i use the television icon. 
It shows up in basicUI in the browser.
` Switch item=TV_Samsung icon="television"`

**Comment by digitaldan** [comment] 2017-08-14 14:56
>The app also crashes when i use the television icon.

Hmm, I just tried this and it works on my android device (Nexus 6), that's very strange.   Is there anything else different?  Are you accessing through the openHAB cloud for instance?

**Comment by digitaldan** [comment] 2017-08-14 15:04
>I compiled it with the fix for #330 but it still crashes. http://openhab/icon/fan_box?state=null&format=SVG returns the correct svg. Here is my stack trace on android 5:

Yes, I can duplicate this as well.  I believe this is an issue with our SVG renderer, unfortunately it looks like the author has stopped updating the library.  We will probably have to look to replace it.

**Comment by jurviz** [comment] 2017-08-14 16:00
No, the app crashes with a local network connection. But it only crashes on my Oneplus One with cyanogen OS 13.1.2. It seems to be related to the OS probably. On a Nexus 7 the app does not crash, but does not show the television icon.

**Comment by digitaldan** [comment] 2017-08-14 16:26
>, unfortunately it looks like the author has stopped updating the library.

I was incorrect here, his website is out of date, but the github project is active, I'll take a look at upgrading

**Comment by digitaldan** [comment] 2017-08-14 16:27
looks like its fixed in upstream, https://github.com/BigBadaboom/androidsvg/pull/99

**Comment by digitaldan** [comment] 2017-08-14 16:36
Ok, I can confirm upgrading fixes the issue, I will submit a PR shortly and do a release.

**Closed** 2017-08-14 16:45 UTC
